# Generated by Django 3.1.1 on 2021-10-05 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('tematica', models.CharField(max_length=250)),
                ('objetivo', models.CharField(max_length=500)),
                ('justificativa', models.CharField(max_length=2000)),
                ('publico_alvo', models.CharField(max_length=250)),
                ('data_criacao', models.DateTimeField(auto_now=True)),
                ('data_atualizacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
