# Generated by Django 3.2.9 on 2021-11-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_auto_20211004_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
