# Generated by Django 3.2.9 on 2021-12-02 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_alter_projetos_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projetos',
            table='Evento',
        ),
    ]
