# Generated by Django 3.2.9 on 2021-12-02 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_alter_projetos_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projetos',
            table='Projeto',
        ),
    ]
