# Generated by Django 3.2.9 on 2021-12-16 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0006_auto_20211213_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projetos',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
    ]
