# Generated by Django 3.2.9 on 2022-01-25 01:33

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0007_auto_20211215_2218'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='projetos',
            managers=[
                ('Objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
